name: whishlist
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  intl: ^0.17.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  freezed: ^0.14.2
  build_runner: ^2.1.0
  json_serializable: ^4.1.4
  flutter_gen_runner: ^3.1.1
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.1

flutter:
  uses-material-design: true
  generate: true
    
flutter_icons:
  android: "launcher_icon"
  image_path: "logo.png"
  ios: true
  remove_alpha_ios: true

